variables:
  IMAGE_TAG: latest
  AR_IMAGE: asia-southeast1-docker.pkg.dev/braided-hangout-438006-k2/landing-page/landing-page

stages:
  - build
  - push
  - deploy

build-job:
  extends:
    - .runner-solarena
  stage: build
  script:
    - docker build -t $AR_IMAGE:$IMAGE_TAG --build-arg="name=Cloud Run" .

push-to-artifact-registry:
  extends:
    - .runner-solarena
  stage: push
  image: google/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file=$GCP_SERVICE_KEY
    - gcloud auth configure-docker asia-southeast1-docker.pkg.dev
    #- docker pull $AR_IMAGE:$IMAGE_TAG
    #- docker tag $AR_IMAGE:$IMAGE_TAG $AR_IMAGE:$IMAGE_TAG
    - docker push $AR_IMAGE:$IMAGE_TAG

deploy-to-cloud-run:
  extends:
    - .runner-solarena
  stage: deploy
  image: google/cloud-sdk:latest
  script:
    - gcloud auth activate-service-account --key-file=$GCP_SERVICE_KEY
    - gcloud run deploy landing-page
        --image $AR_IMAGE:$IMAGE_TAG 
        --project braided-hangout-438006-k2 
        --region asia-northeast1 
        --platform managed 
        --allow-unauthenticated

.runner-solarena:
    tags: [solarena-dev]
    before_script:
        - export PATH=$PATH:/home/gitlab-runner/.nvm/versions/node/v20.12.2/bin
        - node -v
        - pnpm -v
        - pm2 -v
        - tflint -v
        - aws --version
        - ts-node -v
        - git lfs -v
        - flatc --version
    variables:
        GIT_CLEAN_FLAGS: none